src/Entity/Adhesion.php
<?php

namespace App\Entity;

use App\Repository\AdhesionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdhesionRepository::class)
 */
class Adhesion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $datePaiement;

    /**
     * @ORM\Column(type="date")
     */
    private $anneeAdhesion;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $typePaiement;

    /**
     * @ORM\ManyToOne(targetEntity=Adherant::class, inversedBy="adhesions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $adherant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatePaiement(): ?\DateTimeInterface
    {
        return $this->datePaiement;
    }

    public function setDatePaiement(\DateTimeInterface $datePaiement): self
    {
        $this->datePaiement = $datePaiement;

        return $this;
    }

    public function getAnneeAdhesion(): ?\DateTimeInterface
    {
        return $this->anneeAdhesion;
    }

    public function setAnneeAdhesion(\DateTimeInterface $anneeAdhesion): self
    {
        $this->anneeAdhesion = $anneeAdhesion;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getTypePaiement(): ?string
    {
        return $this->typePaiement;
    }

    public function setTypePaiement(string $typePaiement): self
    {
        $this->typePaiement = $typePaiement;

        return $this;
    }

    public function getAdherant(): ?Adherant
    {
        return $this->adherant;
    }

    public function setAdherant(?Adherant $adherant): self
    {
        $this->adherant = $adherant;

        return $this;
    }
}

src/Entity/Sponsor.php
<?php

namespace App\Entity;

use App\Repository\SponsorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SponsorRepository::class)
 */
class Sponsor
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modePayement;

    /**
     * @ORM\Column(type="float")
     */
    private $montant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matriculeFiscal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     */
    private $tel;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;

    /**
     * @ORM\ManyToMany(targetEntity=Evenement::class, mappedBy="sponsors")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getModePayement(): ?string
    {
        return $this->modePayement;
    }

    public function setModePayement(string $modePayement): self
    {
        $this->modePayement = $modePayement;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getMatriculeFiscal(): ?string
    {
        return $this->matriculeFiscal;
    }

    public function setMatriculeFiscal(string $matriculeFiscal): self
    {
        $this->matriculeFiscal = $matriculeFiscal;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getLogo()
    {
        return $this->logo;
    }

    public function setLogo($logo): self
    {
        $this->logo = $logo;

        return $this;
    }



    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->Nom."".$this->logo;;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->addSponsor($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            $evenement->removeSponsor($this);
        }

        return $this;
    }


}

src/Form/AdhesionType.php
<?php

namespace App\Form;

use App\Entity\Adherant;
use App\Entity\Adhesion;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdhesionType extends AbstractType
{

    private function getConfiguration($label,$placeholder,$options = []){
        return array_merge([
            'label'=>$label,
            'attr'=>[
                'placeholder'=>$placeholder
            ]
        ],$options);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('adherant',EntityType::class,['class'=>Adherant::class,
                'choice_label'=> function ($adherant){
                    return $adherant->getPrenom()."".$adherant->getNom();
                },
                'attr'=>['class'=>'form-control form-control-sm'],
            ],$this->getConfiguration("adherant","adherant"))
            ->add('datePaiement',DateType::class,['widget'=>'single_text','attr'=>['class'=>'form-control']],$this->getConfiguration("date","date paiement"))
            ->add('anneeAdhesion',DateType::class,['widget'=>'single_text','attr'=>['class'=>'form-control']],$this->getConfiguration("date adhesion","date adhesion"))
            ->add('montant',NumberType::class,['attr'=>['class'=>'form-control']],$this->getConfiguration("Montant","Montant"))
            ->add('typePaiement',ChoiceType::class, [
                'choices'  => [
                    'Especes' => 'Especes',
                    'Cheque' => 'Cheque',

                ]
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Adhesion::class,
        ]);
    }
}

src/Controller/AdhesionController.php
<?php

namespace App\Controller;

use App\Entity\Adhesion;
use App\Form\AdhesionType;
use App\Repository\AdhesionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
/**
 * @Route("/adhesion")
 */
class AdhesionController extends AbstractController
{
    /**
     * @Route("/", name="adhesions")
     */
    public function index(AdhesionRepository $adhesionRepository): Response
    {
        return $this->render('adhesion/index.html.twig',
        [
            'adhesions'=>$adhesionRepository->findAll()
        ]);
    }

    /**
     * @Route("/new", name="new_adhesion"), methods={"GET","POST"}
     */
    public function new (Request $request):Response
    {
        $adhesion =new Adhesion();
        $form=$this->createForm(AdhesionType::class,$adhesion);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($adhesion);
            $entityManager->flush();
            $this->addFlash(
                'success',
                "adhesion ajouter avec succès"
            );
            return $this->redirectToRoute('adhesions');
        }
        return $this->render('adhesion/new.html.twig',[
            'form'=> $form->createView()
        ]);
    }

    /**
     * @Route ("/{id}/edit" ,name="edit_adhesion")
     */
    public function edit(Request $request,$id) :Response{
        $adhesion=$this->getDoctrine()->getRepository(Adhesion::class)->find($id);
        $form =$this->createForm(AdhesionType::class,$adhesion);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            $this->addFlash(
                'success',
                "adhesion modifier avec succès"
            );
            return $this->redirectToRoute('adhesions');
        }
        return $this->render('adhesion/edit.html.twig',[
            'form'=>$form->createView()
    ]);
    }

    /**
     * @Route ("/{id}",name="delete_adhesion"),methods={"DELETE"}
     */
    public function delete(Request $request, $id){
        $adhesion= $this->getDoctrine()->getRepository(Adhesion::class)->find($id);
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($adhesion);
        $entityManager->flush();
        $this->addFlash(
            'danger',
            "adhesion supprimer avec succès"
        );

        return $this->redirectToRoute('adhesions');
    }

}

templates/adhesion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}modifier adhesion!{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-5">modifier adhesion</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="float-right"> <button type="submit" class="btn btn-primary"><i class="fas fa-new"> modifier</i></button></div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/adhesion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AdhesionController!{% endblock %}

{% block body %}
    <section>

        <h5 class="my-4 dark-grey-text font-weight-bold">Responsive table</h5>

        <!-- Top Table UI -->
        <div class="card p-2 mb-5">

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-lg-3 col-md-12">

                    <!-- Name -->


                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-lg-3 col-md-6">

                    <!-- Blue select -->

                    <!-- /Blue select -->

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-lg-3 col-md-6">


                    <!-- /Blue select -->

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-lg-3 col-md-6">

                    <form class="form-inline md-form mt-2 ml-2">
                        <input class="form-control mt-2" type="text" placeholder="recherche" style="max-width: 150px;">
                        <button class="btn btn-sm btn-primary ml-2 px-1"><i class="fas fa-search"></i> </button>
                    </form>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </div>
        <!-- Top Table UI -->
        <div class="card card-cascade narrower z-depth-1">

            <!-- Card image -->
            <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">

                <div>
                    <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fas fa-th-large mt-0"></i></button>
                    <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fas fa-columns mt-0"></i></button>
                </div>

                <a href="" class="white-text mx-3">Adhesions</a>

                <div>
                    <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fas fa-pencil-alt mt-0"></i></button>
                    <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fas fa-eraser mt-0"></i></button>
                    <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2"><i class="fas fa-info-circle mt-0"></i></button>
                </div>

            </div>
            <!-- /Card image -->

            <div class="px-4">

                <div class="table-responsive">
                    <!-- Table -->
                    <table class="table table-hover mb-0">

                        <!-- Table head -->
                        <thead>
                        <tr>

                            <th class="th-lg"><a>ID <i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">Adherant<i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">date Paiement<i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">annee d'adhesion<i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">montant<i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">type de Paiement<i class="fas fa-sort ml-1"></i></a></th>
                            <th class="th-lg"><a href="">Action<i class="fas fa-sort ml-1"></i></a></th>


                        </tr>
                        </thead>
                        <!-- Table head -->

                        <!-- Table body -->
                        <tbody>
                        {% for ad in adhesions %}
                            <tr>
                                <td>{{ ad.id }}</td>
                                <td> {{ ad.adherant.nom }} {{ ad.adherant.prenom }}</td>
                                <td >{{ ad.datePaiement ? ad.datePaiement|date('Y-m-d') : ''}}</td>
                                <td >{{ ad.anneeAdhesion ? ad.anneeAdhesion|date('Y') : ''}}</td>
                                <td >{{ ad.montant }}</td>
                                <td >{{ ad.typePaiement }}</td>



                                <td><a href="{{ path('edit_adhesion', {'id': ad.id}) }}" class="btn btn-outline-blue btn-rounded btn-sm px-2"><i class="fas fa-pencil-alt mt-0"></i></a>
                                    <a href="#" class="btn btn-outline-yellow btn-rounded btn-sm px-2"><i class="fas fa-info-circle mt-0"></i></a>
                                    <a href="{{ path('delete_adhesion', {'id': ad.id}) }}" class="btn btn-outline-red btn-rounded btn-sm px-2"><i class="fas fa-eraser mt-0"></i></a></td>
                            </tr>

                        {% endfor %}
                        </tbody>
                        <!-- Table body -->
                    </table>
                    <!-- Table -->
                </div>

                <hr class="my-0">

                <!-- Bottom Table UI -->
                <div class="d-flex justify-content-between">

                    <!-- Name -->


                    <!-- Pagination -->
                    <nav class="my-4">
                        <ul class="pagination pagination-circle pg-blue mb-0">

                            <!-- First -->
                            <li class="page-item disabled clearfix d-none d-md-block"><a class="page-link">First</a></li>

                            <!-- Arrow left -->
                            <li class="page-item disabled">
                                <a class="page-link" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>

                            <!-- Numbers -->
                            <li class="page-item active"><a class="page-link">1</a></li>
                            <li class="page-item"><a class="page-link">2</a></li>
                            <li class="page-item clearfix d-none d-md-inline-block"><a class="page-link">3</a></li>
                            <li class="page-item clearfix d-none d-md-inline-block"><a class="page-link">4</a></li>
                            <li class="page-item clearfix d-none d-md-inline-block"><a class="page-link">5</a></li>

                            <!-- Arrow right -->
                            <li class="page-item">
                                <a class="page-link" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>

                            <!-- First -->
                            <li class="page-item clearfix d-none d-md-block"><a class="page-link">Last</a></li>

                        </ul>
                    </nav>
                    <!-- /Pagination -->

                </div>
                <!-- Bottom Table UI -->

            </div>
        </div>
    </section>
{% endblock %}

templates/adhesion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}ajouter adhesion!{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-5">ajouter adhesion</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="float-right"> <button type="submit" class="btn btn-primary"><i class="fas fa-new"> ajouter</i></button></div>
        {{ form_end(form) }}
    </div>
{% endblock %}